### ISSUE TITLE
setting: 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by seokbeom00** [SOPT-all/35-COLLABORATION-SERVER-LOTTE_CINEMA#1]
## 💡 Issue

- 프로젝트 초기 세팅입니다.

## 📝 To-do
- [x] build gradle 작성
- [x] mysql 데이터베이스 연동
- [x] 초기 yml 파일 생성
- [x] 폴더 구조 세팅
