### ISSUE TITLE
feat: 지역별 영화관 리스트 조회 Api 구현

### ISSUE THREAD

**Issue by seokbeom00** [SOPT-all/35-COLLABORATION-SERVER-LOTTE_CINEMA#3]
## 💡 Issue

- 예매하기 단계에서, 지역별로 위치해있는 극장 지점을 조회하는 API 구현

## 📝 To-do
- [x] 필요한 엔티티 생성
- [x] 테스트용 데이터 로컬에 삽입
- [x] 컨트롤러, 서비스, 레포지토리 구현
