### ISSUE TITLE
setting: 커스텀 응답, 에러 세팅

### ISSUE THREAD

**Issue by seokbeom00** [SOPT-all/35-COLLABORATION-SERVER-LOTTE_CINEMA#4]
## 💡 Issue

- 커스텀 응답, 에러에 필요한 클래스 구현

## 📝 To-do
- [x] 응답 Dto 구현
- [x] 성공, 에러 Enum 클래스 구현
- [x] 에러 핸들러 구현
- [x] 커스텀 에러 클래스 구현
