### ISSUE TITLE
feat: 상영관 + 상영시간 리스트 조회 Api 구현

### ISSUE THREAD

**Issue by seokbeom00** [SOPT-all/35-COLLABORATION-SERVER-LOTTE_CINEMA#8]
## 💡 Issue

- 상영관과 상영시간 리스트를 선택한 영화관의 갯수만큼 조회하는 Api입니다.

## 📝 To-do
- [ ] 필요한 엔티티 구현
- [ ] 서비스, 컨트롤러, 레포지토리 구현
- [ ] 랜덤한 세트를 조회하는 로직 구현
